### ISSUE TITLE
Universal pee

### ISSUE THREAD

**Issue by pi0** [enbyautumn/pee.js#1]
Hey 👋 

I wanna use this lib to also make memory leaks in Workers and Node.js? Can this be possible?

Cheers!

**Comment by enbyautumn** [comment]
I'll start working on this right away !

**Comment by Semro** [comment]
can't wait for golden rain

**Comment by enbyautumn** [comment]
A node module for this now exists, https://www.npmjs.com/package/pee.js

**Comment by enbyautumn** [comment]
Have a nice pee!
